### ISSUE TITLE
sum_even_fibonacci.py issue

### ISSUE THREAD

**Issue by cwodarz** [cwodarz/VERSO-UVM-CS-2300-Advanced-Programming-TeamStar#12]
Description: This program is not adding even numbers as intended because the check for even uses b%3==0 instead of b%2==0. 

Steps to Reproduce

First step to reproduce the issue/bug: download the file to an IDE to run it
Second step to reproduce the issue/bug: run the file 
Third step to reproduce the issue/bug: observe that even numbers are not added 
Expected Behavior A clear and concise description of what you expected to happen: only even numbers should have been produced 

Actual Behavior A clear and concise description of what actually happened: odd numbers were produced

Screenshots If applicable, add screenshots to help explain the issue/bug.
<img width="426" alt="Screenshot 2024-04-11 at 10 53 57 AM" src="https://github.com/cwodarz/VERSO-UVM-CS-2300-Advanced-Programming-TeamStar/assets/112415123/e34396f3-958b-4ede-ad34-20db7de4c1c2">

Additional Information
Possible Solution If you have any suggestions for a possible solution, please include them here: change the b%3 to b%2

Priority How critical is this issue/bug? Low, medium, or high priority? Low priority 

Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random? 

Impact What is the impact of this issue/bug? Low, medium, or high? High because the program does not do what we want it to do at all

**Comment by zach-vanzura** [comment]
Fixed issue
