### ISSUE TITLE
Julia decreased the value of array size by 5

### ISSUE THREAD

**Issue by zach-vanzura** [cwodarz/VERSO-UVM-CS-2300-Advanced-Programming-TeamStar#13]
**Reproducing the bug**
Bug is a logic error and will be reproduced every time the code is run.  

**Expected Behavior**
Program is expected to iterate a dataset and remove duplicates.  

**Actual Behavior**
The program doesn't iterate through the entire vector because the value of n is too small

**Additional Info**
I am on macOS using chrome browser

**Solution**
Make size variable n accurate to reflect actual size of the array

bug happens always

impact of this bug is medium.

**Comment by cwodarz** [comment]
Edited the size of variable n so that it no longer decreases the size of the array by 5.
