### ISSUE TITLE
Issue in sum_even_fibonacci.java

### ISSUE THREAD

**Issue by samzimpfer** [cwodarz/VERSO-UVM-CS-2300-Advanced-Programming-TeamStar#14]
On line 9, the condition of the if statement should be (b % 2 == 0), not (b % 1 == 0)
Line 12 should read 'int temp = b', not 'int temp = a'.

Steps to Reproduce

Replace line 9 with 'if (b % 1 == 0) {'
Replace line 12 with 'int temp = a'
Instead of summing all the even numbers, the program 

Expected Behavior: the program sums all even integers less than 4000000 and prints the result.

Actual Behavior: an infinite loop occurs.

Additional Information

Operating System: 14.4.1
Browser: safari
Version: 17.4.1
Any other relevant information
Possible Solution: switch line 9 to 'if (b % 12== 0) {'
     switch line 12 to 'int temp = b'

**Comment by julia-sober** [comment]
Done!
